name: Django timescaledb - Test basic project setup
on:
  push:
    branches: [github-actions]

jobs:
  extract-branch-name:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

  build:
    runs-on: ubuntu-latest
    needs: extract-branch-name
    environment:
      name: ${{ needs.extract-branch-name.outputs.branch_name }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |-
          cd example
          pip install -r requirements.txt

          # Start timescaledb
          docker run -d --name timescaledb -p 5433:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_DB=test timescale/timescaledb:2.1.1-pg13
          sleep 4

          DB_PORT=5433 DB_NAME=test DB_USER=postgres PYTHONPATH=../ python3 manage.py migrate

      - name: Setup project
        run: |-
          echo "Test"
