name: Django timescaledb - Test basic project setup
on:
  push:
    branches: [main]

jobs:
  setup_example_project:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |-
          cd example
          pip install -r requirements.txt

          # Start timescaledb
          docker run -d --name timescaledb -p 5433:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_DB=test timescale/timescaledb:2.1.1-pg13
          
          # Wait for db to be ready
          sleep 4

          # Migrate
          DB_PORT=5433 DB_NAME=test DB_USER=postgres PYTHONPATH=../ python3 manage.py migrate

      - name: Run tests
        run: |-
          DB_PORT=5433 DB_NAME=test DB_USER=postgres PYTHONPATH=../ python3 manage.py test
